# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0cqbrix.common\x1a\x1cgoogle/protobuf/struct.proto\"\x8d\x01\n\x07\x43ontext\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.qbrix.common.Context.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa5\x01\n\x03\x41rm\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x31\n\x08metadata\x18\x05 \x03(\x0b\x32\x1f.qbrix.common.Arm.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x04Pool\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1f\n\x04\x61rms\x18\x03 \x03(\x0b\x32\x11.qbrix.common.Arm\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"\xad\x02\n\nExperiment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07pool_id\x18\x03 \x01(\t\x12\x0e\n\x06policy\x18\x04 \x01(\t\x12\x41\n\rpolicy_params\x18\x05 \x03(\x0b\x32*.qbrix.common.Experiment.PolicyParamsEntry\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\x12\x33\n\x12policy_params_json\x18\t \x01(\x0b\x32\x17.google.protobuf.Struct\x1a\x33\n\x11PolicyParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12HealthCheckRequest\"\x92\x01\n\x13HealthCheckResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.qbrix.common.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXT_METADATAENTRY']._loaded_options = None
  _globals['_CONTEXT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ARM_METADATAENTRY']._loaded_options = None
  _globals['_ARM_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXPERIMENT_POLICYPARAMSENTRY']._loaded_options = None
  _globals['_EXPERIMENT_POLICYPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CONTEXT']._serialized_start=61
  _globals['_CONTEXT']._serialized_end=202
  _globals['_CONTEXT_METADATAENTRY']._serialized_start=155
  _globals['_CONTEXT_METADATAENTRY']._serialized_end=202
  _globals['_ARM']._serialized_start=205
  _globals['_ARM']._serialized_end=370
  _globals['_ARM_METADATAENTRY']._serialized_start=155
  _globals['_ARM_METADATAENTRY']._serialized_end=202
  _globals['_POOL']._serialized_start=372
  _globals['_POOL']._serialized_end=477
  _globals['_EXPERIMENT']._serialized_start=480
  _globals['_EXPERIMENT']._serialized_end=781
  _globals['_EXPERIMENT_POLICYPARAMSENTRY']._serialized_start=730
  _globals['_EXPERIMENT_POLICYPARAMSENTRY']._serialized_end=781
  _globals['_HEALTHCHECKREQUEST']._serialized_start=783
  _globals['_HEALTHCHECKREQUEST']._serialized_end=803
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=806
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=952
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=894
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=952
# @@protoc_insertion_point(module_scope)
