"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Context(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    VECTOR_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    PROPERTIES_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    @_builtins.property
    def vector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """pre-encoded feature vector. escape hatch for callers holding their own
        embeddings; prefer `properties` and let qbrix own the encoding.
        """

    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    @_builtins.property
    def properties(self) -> _struct_pb2.Struct:
        """named request properties, encoded server-side against the experiment's
        declared context schema. Struct rather than a string map so a number
        stays a number.
        """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        vector: _abc.Iterable[_builtins.float] | None = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        properties: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["properties", b"properties"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "metadata", b"metadata", "properties", b"properties", "vector", b"vector"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Context: _TypeAlias = Context  # noqa: Y015

@_typing.final
class Arm(_message.Message):
    """Arm representation"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    index: _builtins.int
    is_active: _builtins.bool
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        index: _builtins.int = ...,
        is_active: _builtins.bool = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "index", b"index", "is_active", b"is_active", "metadata", b"metadata", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Arm: _TypeAlias = Arm  # noqa: Y015

@_typing.final
class Pool(_message.Message):
    """Pool of arms"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    ARMS_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    created_at: _builtins.str
    """ISO 8601"""
    updated_at: _builtins.str
    """ISO 8601"""
    @_builtins.property
    def arms(self) -> _containers.RepeatedCompositeFieldContainer[Global___Arm]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        arms: _abc.Iterable[Global___Arm] | None = ...,
        created_at: _builtins.str = ...,
        updated_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arms", b"arms", "created_at", b"created_at", "id", b"id", "name", b"name", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Pool: _TypeAlias = Pool  # noqa: Y015

@_typing.final
class Experiment(_message.Message):
    """Experiment configuration"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PolicyParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    POOL_ID_FIELD_NUMBER: _builtins.int
    POLICY_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_JSON_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    pool_id: _builtins.str
    policy: _builtins.str
    """e.g., "thompson_sampling", "ucb", "epsilon_greedy" """
    enabled: _builtins.bool
    created_at: _builtins.str
    """ISO 8601"""
    updated_at: _builtins.str
    """ISO 8601"""
    @_builtins.property
    def policy_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """deprecated: use policy_params_json"""

    @_builtins.property
    def policy_params_json(self) -> _struct_pb2.Struct:
        """full-fidelity policy params"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        pool_id: _builtins.str = ...,
        policy: _builtins.str = ...,
        policy_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        enabled: _builtins.bool = ...,
        created_at: _builtins.str = ...,
        updated_at: _builtins.str = ...,
        policy_params_json: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["policy_params_json", b"policy_params_json"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "enabled", b"enabled", "id", b"id", "name", b"name", "policy", b"policy", "policy_params", b"policy_params", "policy_params_json", b"policy_params_json", "pool_id", b"pool_id", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Experiment: _TypeAlias = Experiment  # noqa: Y015

@_typing.final
class HealthCheckRequest(_message.Message):
    """Health check"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthCheckRequest: _TypeAlias = HealthCheckRequest  # noqa: Y015

@_typing.final
class HealthCheckResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ServingStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ServingStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HealthCheckResponse._ServingStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: HealthCheckResponse._ServingStatus.ValueType  # 0
        SERVING: HealthCheckResponse._ServingStatus.ValueType  # 1
        NOT_SERVING: HealthCheckResponse._ServingStatus.ValueType  # 2

    class ServingStatus(_ServingStatus, metaclass=_ServingStatusEnumTypeWrapper): ...
    UNKNOWN: HealthCheckResponse.ServingStatus.ValueType  # 0
    SERVING: HealthCheckResponse.ServingStatus.ValueType  # 1
    NOT_SERVING: HealthCheckResponse.ServingStatus.ValueType  # 2

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___HealthCheckResponse.ServingStatus.ValueType
    def __init__(
        self,
        *,
        status: Global___HealthCheckResponse.ServingStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthCheckResponse: _TypeAlias = HealthCheckResponse  # noqa: Y015
