"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
from qbrix._transport._grpc._proto import common_pb2 as _common_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreatePoolRequest(_message.Message):
    """Pool management"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ARMS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def arms(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Arm]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        arms: _abc.Iterable[_common_pb2.Arm] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arms", b"arms", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePoolRequest: _TypeAlias = CreatePoolRequest  # noqa: Y015

@_typing.final
class CreatePoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePoolResponse: _TypeAlias = CreatePoolResponse  # noqa: Y015

@_typing.final
class GetPoolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPoolRequest: _TypeAlias = GetPoolRequest  # noqa: Y015

@_typing.final
class GetPoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPoolResponse: _TypeAlias = GetPoolResponse  # noqa: Y015

@_typing.final
class DeletePoolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeletePoolRequest: _TypeAlias = DeletePoolRequest  # noqa: Y015

@_typing.final
class DeletePoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeletePoolResponse: _TypeAlias = DeletePoolResponse  # noqa: Y015

@_typing.final
class ListPoolsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPoolsRequest: _TypeAlias = ListPoolsRequest  # noqa: Y015

@_typing.final
class ListPoolsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOLS_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    @_builtins.property
    def pools(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Pool]: ...
    def __init__(
        self,
        *,
        pools: _abc.Iterable[_common_pb2.Pool] | None = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "offset", b"offset", "pools", b"pools"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPoolsResponse: _TypeAlias = ListPoolsResponse  # noqa: Y015

@_typing.final
class UpdatePoolRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    name: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
        name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "name", b"name", "pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...

Global___UpdatePoolRequest: _TypeAlias = UpdatePoolRequest  # noqa: Y015

@_typing.final
class UpdatePoolResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdatePoolResponse: _TypeAlias = UpdatePoolResponse  # noqa: Y015

@_typing.final
class ExperimentDetail(_message.Message):
    """Experiment detail wrapper"""

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExperimentDetail: _TypeAlias = ExperimentDetail  # noqa: Y015

@_typing.final
class CreateExperimentRequest(_message.Message):
    """Experiment management"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PolicyParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    POOL_ID_FIELD_NUMBER: _builtins.int
    POLICY_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_JSON_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    pool_id: _builtins.str
    policy: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def policy_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """deprecated: use policy_params_json"""

    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig:
        """Feature gate config"""

    @_builtins.property
    def policy_params_json(self) -> _struct_pb2.Struct:
        """full-fidelity policy params. the string map above cannot carry a
        context_schema (a list of objects) — it arrives str()-ed and fails to
        parse. set this and the map is ignored.
        """

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        pool_id: _builtins.str = ...,
        policy: _builtins.str = ...,
        policy_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        enabled: _builtins.bool = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        policy_params_json: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["feature_gate", b"feature_gate", "policy_params_json", b"policy_params_json"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "feature_gate", b"feature_gate", "name", b"name", "policy", b"policy", "policy_params", b"policy_params", "policy_params_json", b"policy_params_json", "pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateExperimentRequest: _TypeAlias = CreateExperimentRequest  # noqa: Y015

@_typing.final
class FeatureGateConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    ROLLOUT_PERCENTAGE_FIELD_NUMBER: _builtins.int
    DEFAULT_ARM_ID_FIELD_NUMBER: _builtins.int
    SCHEDULE_FIELD_NUMBER: _builtins.int
    ACTIVE_HOURS_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    RULES_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    rollout_percentage: _builtins.float
    """0.0 - 100.0"""
    default_arm_id: _builtins.str
    """arm to return when gated"""
    timezone: _builtins.str
    """e.g., "UTC", "America/New_York" """
    @_builtins.property
    def schedule(self) -> Global___ScheduleConfig: ...
    @_builtins.property
    def active_hours(self) -> Global___ActiveHoursConfig: ...
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___RuleConfig]: ...
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        rollout_percentage: _builtins.float = ...,
        default_arm_id: _builtins.str = ...,
        schedule: Global___ScheduleConfig | None = ...,
        active_hours: Global___ActiveHoursConfig | None = ...,
        timezone: _builtins.str = ...,
        rules: _abc.Iterable[Global___RuleConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["active_hours", b"active_hours", "schedule", b"schedule"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_hours", b"active_hours", "default_arm_id", b"default_arm_id", "enabled", b"enabled", "rollout_percentage", b"rollout_percentage", "rules", b"rules", "schedule", b"schedule", "timezone", b"timezone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FeatureGateConfig: _TypeAlias = FeatureGateConfig  # noqa: Y015

@_typing.final
class ScheduleConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    END_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    start_timestamp_ms: _builtins.int
    end_timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        start_timestamp_ms: _builtins.int | None = ...,
        end_timestamp_ms: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_end_timestamp_ms", b"_end_timestamp_ms", "_start_timestamp_ms", b"_start_timestamp_ms", "end_timestamp_ms", b"end_timestamp_ms", "start_timestamp_ms", b"start_timestamp_ms"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_end_timestamp_ms", b"_end_timestamp_ms", "_start_timestamp_ms", b"_start_timestamp_ms", "end_timestamp_ms", b"end_timestamp_ms", "start_timestamp_ms", b"start_timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__end_timestamp_ms: _TypeAlias = _typing.Literal["end_timestamp_ms"]  # noqa: Y015
    _WhichOneofArgType__end_timestamp_ms: _TypeAlias = _typing.Literal["_end_timestamp_ms", b"_end_timestamp_ms"]  # noqa: Y015
    _WhichOneofReturnType__start_timestamp_ms: _TypeAlias = _typing.Literal["start_timestamp_ms"]  # noqa: Y015
    _WhichOneofArgType__start_timestamp_ms: _TypeAlias = _typing.Literal["_start_timestamp_ms", b"_start_timestamp_ms"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_timestamp_ms) -> _WhichOneofReturnType__end_timestamp_ms | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_timestamp_ms) -> _WhichOneofReturnType__start_timestamp_ms | None: ...

Global___ScheduleConfig: _TypeAlias = ScheduleConfig  # noqa: Y015

@_typing.final
class ActiveHoursConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    start: _builtins.str
    """HH:MM format"""
    end: _builtins.str
    """HH:MM format"""
    def __init__(
        self,
        *,
        start: _builtins.str | None = ...,
        end: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_end", b"_end", "_start", b"_start", "end", b"end", "start", b"start"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_end", b"_end", "_start", b"_start", "end", b"end", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__end: _TypeAlias = _typing.Literal["end"]  # noqa: Y015
    _WhichOneofArgType__end: _TypeAlias = _typing.Literal["_end", b"_end"]  # noqa: Y015
    _WhichOneofReturnType__start: _TypeAlias = _typing.Literal["start"]  # noqa: Y015
    _WhichOneofArgType__start: _TypeAlias = _typing.Literal["_start", b"_start"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end) -> _WhichOneofReturnType__end | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start) -> _WhichOneofReturnType__start | None: ...

Global___ActiveHoursConfig: _TypeAlias = ActiveHoursConfig  # noqa: Y015

@_typing.final
class RuleConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    OPERATOR_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    ARM_ID_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    """metadata key to evaluate"""
    operator: _builtins.str
    """==, !=, >, <, contains, in, etc."""
    value: _builtins.str
    """value to compare against (JSON encoded for complex types)"""
    arm_id: _builtins.str
    """arm to return if rule matches"""
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        operator: _builtins.str = ...,
        value: _builtins.str = ...,
        arm_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arm_id", b"arm_id", "key", b"key", "operator", b"operator", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuleConfig: _TypeAlias = RuleConfig  # noqa: Y015

@_typing.final
class CreateExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateExperimentResponse: _TypeAlias = CreateExperimentResponse  # noqa: Y015

@_typing.final
class GetExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetExperimentRequest: _TypeAlias = GetExperimentRequest  # noqa: Y015

@_typing.final
class GetExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetExperimentResponse: _TypeAlias = GetExperimentResponse  # noqa: Y015

@_typing.final
class UpdateExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PolicyParamsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POLICY_PARAMS_JSON_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    enabled: _builtins.bool
    @_builtins.property
    def policy_params(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """deprecated: use policy_params_json"""

    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def policy_params_json(self) -> _struct_pb2.Struct:
        """full-fidelity policy params"""

    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        enabled: _builtins.bool | None = ...,
        policy_params: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        policy_params_json: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_feature_gate", b"_feature_gate", "enabled", b"enabled", "feature_gate", b"feature_gate", "policy_params_json", b"policy_params_json"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_feature_gate", b"_feature_gate", "enabled", b"enabled", "experiment_id", b"experiment_id", "feature_gate", b"feature_gate", "policy_params", b"policy_params", "policy_params_json", b"policy_params_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    _WhichOneofReturnType__feature_gate: _TypeAlias = _typing.Literal["feature_gate"]  # noqa: Y015
    _WhichOneofArgType__feature_gate: _TypeAlias = _typing.Literal["_feature_gate", b"_feature_gate"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__feature_gate) -> _WhichOneofReturnType__feature_gate | None: ...

Global___UpdateExperimentRequest: _TypeAlias = UpdateExperimentRequest  # noqa: Y015

@_typing.final
class UpdateExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_FIELD_NUMBER: _builtins.int
    FEATURE_GATE_FIELD_NUMBER: _builtins.int
    POOL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiment(self) -> _common_pb2.Experiment: ...
    @_builtins.property
    def feature_gate(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def pool(self) -> _common_pb2.Pool: ...
    def __init__(
        self,
        *,
        experiment: _common_pb2.Experiment | None = ...,
        feature_gate: Global___FeatureGateConfig | None = ...,
        pool: _common_pb2.Pool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment", b"experiment", "feature_gate", b"feature_gate", "pool", b"pool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateExperimentResponse: _TypeAlias = UpdateExperimentResponse  # noqa: Y015

@_typing.final
class DeleteExperimentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteExperimentRequest: _TypeAlias = DeleteExperimentRequest  # noqa: Y015

@_typing.final
class DeleteExperimentResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteExperimentResponse: _TypeAlias = DeleteExperimentResponse  # noqa: Y015

@_typing.final
class ListExperimentsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    SEARCH_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    search: _builtins.str
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
        search: _builtins.str | None = ...,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_search", b"_search", "enabled", b"enabled", "search", b"search"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "_search", b"_search", "enabled", b"enabled", "limit", b"limit", "offset", b"offset", "search", b"search"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    _WhichOneofReturnType__search: _TypeAlias = _typing.Literal["search"]  # noqa: Y015
    _WhichOneofArgType__search: _TypeAlias = _typing.Literal["_search", b"_search"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__search) -> _WhichOneofReturnType__search | None: ...

Global___ListExperimentsRequest: _TypeAlias = ListExperimentsRequest  # noqa: Y015

@_typing.final
class ListExperimentsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENTS_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    offset: _builtins.int
    @_builtins.property
    def experiments(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Experiment]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExperimentDetail]: ...
    def __init__(
        self,
        *,
        experiments: _abc.Iterable[_common_pb2.Experiment] | None = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
        items: _abc.Iterable[Global___ExperimentDetail] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiments", b"experiments", "items", b"items", "limit", b"limit", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListExperimentsResponse: _TypeAlias = ListExperimentsResponse  # noqa: Y015

@_typing.final
class ListPoolExperimentsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POOL_ID_FIELD_NUMBER: _builtins.int
    pool_id: _builtins.str
    def __init__(
        self,
        *,
        pool_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pool_id", b"pool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPoolExperimentsRequest: _TypeAlias = ListPoolExperimentsRequest  # noqa: Y015

@_typing.final
class ListPoolExperimentsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENTS_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def experiments(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Experiment]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExperimentDetail]: ...
    def __init__(
        self,
        *,
        experiments: _abc.Iterable[_common_pb2.Experiment] | None = ...,
        items: _abc.Iterable[Global___ExperimentDetail] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiments", b"experiments", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPoolExperimentsResponse: _TypeAlias = ListPoolExperimentsResponse  # noqa: Y015

@_typing.final
class CreateGateConfigRequest(_message.Message):
    """Gate config management"""

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    @_builtins.property
    def config(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        config: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateGateConfigRequest: _TypeAlias = CreateGateConfigRequest  # noqa: Y015

@_typing.final
class CreateGateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        config: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateGateConfigResponse: _TypeAlias = CreateGateConfigResponse  # noqa: Y015

@_typing.final
class GetGateConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetGateConfigRequest: _TypeAlias = GetGateConfigRequest  # noqa: Y015

@_typing.final
class GetGateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        config: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetGateConfigResponse: _TypeAlias = GetGateConfigResponse  # noqa: Y015

@_typing.final
class UpdateGateConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    UPDATE_MASK_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    @_builtins.property
    def config(self) -> Global___FeatureGateConfig: ...
    @_builtins.property
    def update_mask(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """fields of `config` to apply. empty replaces the whole gate."""

    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        config: Global___FeatureGateConfig | None = ...,
        update_mask: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "experiment_id", b"experiment_id", "update_mask", b"update_mask"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateGateConfigRequest: _TypeAlias = UpdateGateConfigRequest  # noqa: Y015

@_typing.final
class UpdateGateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> Global___FeatureGateConfig: ...
    def __init__(
        self,
        *,
        config: Global___FeatureGateConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateGateConfigResponse: _TypeAlias = UpdateGateConfigResponse  # noqa: Y015

@_typing.final
class DeleteGateConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteGateConfigRequest: _TypeAlias = DeleteGateConfigRequest  # noqa: Y015

@_typing.final
class DeleteGateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteGateConfigResponse: _TypeAlias = DeleteGateConfigResponse  # noqa: Y015

@_typing.final
class SelectRequest(_message.Message):
    """Selection (external API)"""

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENT_ID_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    experiment_id: _builtins.str
    @_builtins.property
    def context(self) -> _common_pb2.Context: ...
    def __init__(
        self,
        *,
        experiment_id: _builtins.str = ...,
        context: _common_pb2.Context | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "experiment_id", b"experiment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SelectRequest: _TypeAlias = SelectRequest  # noqa: Y015

@_typing.final
class SelectResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ARM_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    IS_DEFAULT_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    is_default: _builtins.bool
    """True if returned by feature gate, not bandit"""
    @_builtins.property
    def arm(self) -> _common_pb2.Arm: ...
    def __init__(
        self,
        *,
        arm: _common_pb2.Arm | None = ...,
        request_id: _builtins.str = ...,
        is_default: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["arm", b"arm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arm", b"arm", "is_default", b"is_default", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SelectResponse: _TypeAlias = SelectResponse  # noqa: Y015

@_typing.final
class FeedbackRequest(_message.Message):
    """Feedback"""

    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    REWARD_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """signed token from SelectResponse containing all selection context"""
    reward: _builtins.float
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        reward: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["request_id", b"request_id", "reward", b"reward"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FeedbackRequest: _TypeAlias = FeedbackRequest  # noqa: Y015

@_typing.final
class FeedbackResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FeedbackResponse: _TypeAlias = FeedbackResponse  # noqa: Y015

@_typing.final
class ListPoliciesRequest(_message.Message):
    """Policy introspection"""

    DESCRIPTOR: _descriptor.Descriptor

    REWARD_TYPE_FIELD_NUMBER: _builtins.int
    reward_type: _builtins.str
    """binary | bounded | continuous"""
    def __init__(
        self,
        *,
        reward_type: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_reward_type", b"_reward_type", "reward_type", b"reward_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_reward_type", b"_reward_type", "reward_type", b"reward_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__reward_type: _TypeAlias = _typing.Literal["reward_type"]  # noqa: Y015
    _WhichOneofArgType__reward_type: _TypeAlias = _typing.Literal["_reward_type", b"_reward_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__reward_type) -> _WhichOneofReturnType__reward_type | None: ...

Global___ListPoliciesRequest: _TypeAlias = ListPoliciesRequest  # noqa: Y015

@_typing.final
class PolicyParam(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ConstraintsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.float
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    DEFAULT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    CONSTRAINTS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: _builtins.str
    """"integer" | "number" """
    required: _builtins.bool
    description: _builtins.str
    @_builtins.property
    def default(self) -> _struct_pb2.Value:
        """default is Any|None -> Value"""

    @_builtins.property
    def constraints(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]:
        """gt | gte | lt | lte"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: _builtins.str = ...,
        required: _builtins.bool = ...,
        default: _struct_pb2.Value | None = ...,
        description: _builtins.str = ...,
        constraints: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["default", b"default"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["constraints", b"constraints", "default", b"default", "description", b"description", "name", b"name", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PolicyParam: _TypeAlias = PolicyParam  # noqa: Y015

@_typing.final
class Policy(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    REWARD_TYPES_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    USER_PARAMS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    category: _builtins.str
    """stochastic | contextual | adversarial"""
    description: _builtins.str
    @_builtins.property
    def reward_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def user_params(self) -> _containers.RepeatedCompositeFieldContainer[Global___PolicyParam]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        category: _builtins.str = ...,
        reward_types: _abc.Iterable[_builtins.str] | None = ...,
        description: _builtins.str = ...,
        user_params: _abc.Iterable[Global___PolicyParam] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "description", b"description", "name", b"name", "reward_types", b"reward_types", "user_params", b"user_params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Policy: _TypeAlias = Policy  # noqa: Y015

@_typing.final
class ListPoliciesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POLICIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def policies(self) -> _containers.RepeatedCompositeFieldContainer[Global___Policy]: ...
    def __init__(
        self,
        *,
        policies: _abc.Iterable[Global___Policy] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["policies", b"policies"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPoliciesResponse: _TypeAlias = ListPoliciesResponse  # noqa: Y015
