# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qbrix._transport._grpc._proto import common_pb2 as common__pb2
from qbrix._transport._grpc._proto import proxy_pb2 as proxy__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProxyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePool = channel.unary_unary(
                '/qbrix.proxy.ProxyService/CreatePool',
                request_serializer=proxy__pb2.CreatePoolRequest.SerializeToString,
                response_deserializer=proxy__pb2.CreatePoolResponse.FromString,
                _registered_method=True)
        self.GetPool = channel.unary_unary(
                '/qbrix.proxy.ProxyService/GetPool',
                request_serializer=proxy__pb2.GetPoolRequest.SerializeToString,
                response_deserializer=proxy__pb2.GetPoolResponse.FromString,
                _registered_method=True)
        self.ListPools = channel.unary_unary(
                '/qbrix.proxy.ProxyService/ListPools',
                request_serializer=proxy__pb2.ListPoolsRequest.SerializeToString,
                response_deserializer=proxy__pb2.ListPoolsResponse.FromString,
                _registered_method=True)
        self.UpdatePool = channel.unary_unary(
                '/qbrix.proxy.ProxyService/UpdatePool',
                request_serializer=proxy__pb2.UpdatePoolRequest.SerializeToString,
                response_deserializer=proxy__pb2.UpdatePoolResponse.FromString,
                _registered_method=True)
        self.DeletePool = channel.unary_unary(
                '/qbrix.proxy.ProxyService/DeletePool',
                request_serializer=proxy__pb2.DeletePoolRequest.SerializeToString,
                response_deserializer=proxy__pb2.DeletePoolResponse.FromString,
                _registered_method=True)
        self.CreateExperiment = channel.unary_unary(
                '/qbrix.proxy.ProxyService/CreateExperiment',
                request_serializer=proxy__pb2.CreateExperimentRequest.SerializeToString,
                response_deserializer=proxy__pb2.CreateExperimentResponse.FromString,
                _registered_method=True)
        self.GetExperiment = channel.unary_unary(
                '/qbrix.proxy.ProxyService/GetExperiment',
                request_serializer=proxy__pb2.GetExperimentRequest.SerializeToString,
                response_deserializer=proxy__pb2.GetExperimentResponse.FromString,
                _registered_method=True)
        self.ListExperiments = channel.unary_unary(
                '/qbrix.proxy.ProxyService/ListExperiments',
                request_serializer=proxy__pb2.ListExperimentsRequest.SerializeToString,
                response_deserializer=proxy__pb2.ListExperimentsResponse.FromString,
                _registered_method=True)
        self.ListPoolExperiments = channel.unary_unary(
                '/qbrix.proxy.ProxyService/ListPoolExperiments',
                request_serializer=proxy__pb2.ListPoolExperimentsRequest.SerializeToString,
                response_deserializer=proxy__pb2.ListPoolExperimentsResponse.FromString,
                _registered_method=True)
        self.UpdateExperiment = channel.unary_unary(
                '/qbrix.proxy.ProxyService/UpdateExperiment',
                request_serializer=proxy__pb2.UpdateExperimentRequest.SerializeToString,
                response_deserializer=proxy__pb2.UpdateExperimentResponse.FromString,
                _registered_method=True)
        self.DeleteExperiment = channel.unary_unary(
                '/qbrix.proxy.ProxyService/DeleteExperiment',
                request_serializer=proxy__pb2.DeleteExperimentRequest.SerializeToString,
                response_deserializer=proxy__pb2.DeleteExperimentResponse.FromString,
                _registered_method=True)
        self.CreateGateConfig = channel.unary_unary(
                '/qbrix.proxy.ProxyService/CreateGateConfig',
                request_serializer=proxy__pb2.CreateGateConfigRequest.SerializeToString,
                response_deserializer=proxy__pb2.CreateGateConfigResponse.FromString,
                _registered_method=True)
        self.GetGateConfig = channel.unary_unary(
                '/qbrix.proxy.ProxyService/GetGateConfig',
                request_serializer=proxy__pb2.GetGateConfigRequest.SerializeToString,
                response_deserializer=proxy__pb2.GetGateConfigResponse.FromString,
                _registered_method=True)
        self.UpdateGateConfig = channel.unary_unary(
                '/qbrix.proxy.ProxyService/UpdateGateConfig',
                request_serializer=proxy__pb2.UpdateGateConfigRequest.SerializeToString,
                response_deserializer=proxy__pb2.UpdateGateConfigResponse.FromString,
                _registered_method=True)
        self.DeleteGateConfig = channel.unary_unary(
                '/qbrix.proxy.ProxyService/DeleteGateConfig',
                request_serializer=proxy__pb2.DeleteGateConfigRequest.SerializeToString,
                response_deserializer=proxy__pb2.DeleteGateConfigResponse.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/qbrix.proxy.ProxyService/Select',
                request_serializer=proxy__pb2.SelectRequest.SerializeToString,
                response_deserializer=proxy__pb2.SelectResponse.FromString,
                _registered_method=True)
        self.Feedback = channel.unary_unary(
                '/qbrix.proxy.ProxyService/Feedback',
                request_serializer=proxy__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=proxy__pb2.FeedbackResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/qbrix.proxy.ProxyService/Health',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ProxyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExperiments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPoolExperiments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExperiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Feedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePool': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePool,
                    request_deserializer=proxy__pb2.CreatePoolRequest.FromString,
                    response_serializer=proxy__pb2.CreatePoolResponse.SerializeToString,
            ),
            'GetPool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPool,
                    request_deserializer=proxy__pb2.GetPoolRequest.FromString,
                    response_serializer=proxy__pb2.GetPoolResponse.SerializeToString,
            ),
            'ListPools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPools,
                    request_deserializer=proxy__pb2.ListPoolsRequest.FromString,
                    response_serializer=proxy__pb2.ListPoolsResponse.SerializeToString,
            ),
            'UpdatePool': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePool,
                    request_deserializer=proxy__pb2.UpdatePoolRequest.FromString,
                    response_serializer=proxy__pb2.UpdatePoolResponse.SerializeToString,
            ),
            'DeletePool': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePool,
                    request_deserializer=proxy__pb2.DeletePoolRequest.FromString,
                    response_serializer=proxy__pb2.DeletePoolResponse.SerializeToString,
            ),
            'CreateExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExperiment,
                    request_deserializer=proxy__pb2.CreateExperimentRequest.FromString,
                    response_serializer=proxy__pb2.CreateExperimentResponse.SerializeToString,
            ),
            'GetExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperiment,
                    request_deserializer=proxy__pb2.GetExperimentRequest.FromString,
                    response_serializer=proxy__pb2.GetExperimentResponse.SerializeToString,
            ),
            'ListExperiments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExperiments,
                    request_deserializer=proxy__pb2.ListExperimentsRequest.FromString,
                    response_serializer=proxy__pb2.ListExperimentsResponse.SerializeToString,
            ),
            'ListPoolExperiments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPoolExperiments,
                    request_deserializer=proxy__pb2.ListPoolExperimentsRequest.FromString,
                    response_serializer=proxy__pb2.ListPoolExperimentsResponse.SerializeToString,
            ),
            'UpdateExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExperiment,
                    request_deserializer=proxy__pb2.UpdateExperimentRequest.FromString,
                    response_serializer=proxy__pb2.UpdateExperimentResponse.SerializeToString,
            ),
            'DeleteExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExperiment,
                    request_deserializer=proxy__pb2.DeleteExperimentRequest.FromString,
                    response_serializer=proxy__pb2.DeleteExperimentResponse.SerializeToString,
            ),
            'CreateGateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGateConfig,
                    request_deserializer=proxy__pb2.CreateGateConfigRequest.FromString,
                    response_serializer=proxy__pb2.CreateGateConfigResponse.SerializeToString,
            ),
            'GetGateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGateConfig,
                    request_deserializer=proxy__pb2.GetGateConfigRequest.FromString,
                    response_serializer=proxy__pb2.GetGateConfigResponse.SerializeToString,
            ),
            'UpdateGateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGateConfig,
                    request_deserializer=proxy__pb2.UpdateGateConfigRequest.FromString,
                    response_serializer=proxy__pb2.UpdateGateConfigResponse.SerializeToString,
            ),
            'DeleteGateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGateConfig,
                    request_deserializer=proxy__pb2.DeleteGateConfigRequest.FromString,
                    response_serializer=proxy__pb2.DeleteGateConfigResponse.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=proxy__pb2.SelectRequest.FromString,
                    response_serializer=proxy__pb2.SelectResponse.SerializeToString,
            ),
            'Feedback': grpc.unary_unary_rpc_method_handler(
                    servicer.Feedback,
                    request_deserializer=proxy__pb2.FeedbackRequest.FromString,
                    response_serializer=proxy__pb2.FeedbackResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qbrix.proxy.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qbrix.proxy.ProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProxyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/CreatePool',
            proxy__pb2.CreatePoolRequest.SerializeToString,
            proxy__pb2.CreatePoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/GetPool',
            proxy__pb2.GetPoolRequest.SerializeToString,
            proxy__pb2.GetPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/ListPools',
            proxy__pb2.ListPoolsRequest.SerializeToString,
            proxy__pb2.ListPoolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/UpdatePool',
            proxy__pb2.UpdatePoolRequest.SerializeToString,
            proxy__pb2.UpdatePoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/DeletePool',
            proxy__pb2.DeletePoolRequest.SerializeToString,
            proxy__pb2.DeletePoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/CreateExperiment',
            proxy__pb2.CreateExperimentRequest.SerializeToString,
            proxy__pb2.CreateExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/GetExperiment',
            proxy__pb2.GetExperimentRequest.SerializeToString,
            proxy__pb2.GetExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExperiments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/ListExperiments',
            proxy__pb2.ListExperimentsRequest.SerializeToString,
            proxy__pb2.ListExperimentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPoolExperiments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/ListPoolExperiments',
            proxy__pb2.ListPoolExperimentsRequest.SerializeToString,
            proxy__pb2.ListPoolExperimentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/UpdateExperiment',
            proxy__pb2.UpdateExperimentRequest.SerializeToString,
            proxy__pb2.UpdateExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/DeleteExperiment',
            proxy__pb2.DeleteExperimentRequest.SerializeToString,
            proxy__pb2.DeleteExperimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/CreateGateConfig',
            proxy__pb2.CreateGateConfigRequest.SerializeToString,
            proxy__pb2.CreateGateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/GetGateConfig',
            proxy__pb2.GetGateConfigRequest.SerializeToString,
            proxy__pb2.GetGateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/UpdateGateConfig',
            proxy__pb2.UpdateGateConfigRequest.SerializeToString,
            proxy__pb2.UpdateGateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/DeleteGateConfig',
            proxy__pb2.DeleteGateConfigRequest.SerializeToString,
            proxy__pb2.DeleteGateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/Select',
            proxy__pb2.SelectRequest.SerializeToString,
            proxy__pb2.SelectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Feedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/Feedback',
            proxy__pb2.FeedbackRequest.SerializeToString,
            proxy__pb2.FeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qbrix.proxy.ProxyService/Health',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
